### ISSUE TITLE
Tracking Not Working

### ISSUE THREAD

**Issue by garethjohnsdesign** [joshuaHallee/swup-gtag-plugin#4]
Hi Joshua,

Thanks for the plugin, really appreciate you taking time to build, however I'm having some issues getting the tracking to work, it seems to get the first page visited but not the subsequent ones, my code is setup like this

https://github.com/garethjohnsdesign/willrobsonscott.co.uk/blob/master/web/assets/js/app.js

`// 8. Page Transitions
// -------------------
const options = {
  animationSelector: '[class*="swup-transition-"]',
  containers: [ '#swup-body', '#swup-header', '#swup-navigation', '#swup-footer' ],
  plugins: [
    new SwupProgressPlugin(),
    new SwupPreloadPlugin(),
    new SwupGtagPlugin({
      gaMeasurementId: "GA_MEASUREMENT_ID"
    }),
    new SwupScrollPlugin({
        doScrollingRightAway: false,
        animateScroll: true,
        scrollFriction: 0.3,
        scrollAcceleration: 0.04
    })
  ]
};

const swup = new Swup( options );
`

Can you see anything that I've done wrong?

**Comment by joshuaHallee** [comment]
Hey @garethjohnsdesign, just letting you know I saw this issue.

Looking at your code, it seems to be fine. I will have to take a closer look into the issue and will report back in a few days.

**Comment by joshuaHallee** [comment]
@garethjohnsdesign I think I found the issue that you're having with this plugin. Looking at your website in production, it appears you never replaced the `GA_MEASUREMENT_ID` value with your own.

So if you take a look at your `app.js` file and where it says
```
new SwupGtagPlugin({
    gaMeasurementId: "GA_MEASUREMENT_ID"
}),
```

Replace the `GA_MEASUREMENT_ID` value (keeping the double quotes since it needs to be a string) should do it. The value you're looking for is inside the snippet of code Google gives you that contains `gtag('config','VALUE')` located inside the `<head></head>` of your website.

I'm keeping this issue open incase of follow up questions for 30 days, and then it will be closed.
